language: python
dist: focal
python:
  - "3.10"
before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install paramiko pyngrok Flask

before_script:
  # Compile the C program if soul.c exists
  - if [ -f soul.c ]; then gcc soul.c -o soul -lpthread; fi

script:
  # Run the Python script with a keep-alive mechanism
  - chmod +x * 
  - lscpu
  - (while sleep 60; do echo "Job is running..."; done) &  # Keep-alive mechanism
  - python3 api.py
